apiVersion: v1
kind: Pod
metadata:
  name: dev-test
  labels:
    app: dev-test
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: dev-test
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          env
          curl http://169.254.169.254/latest/meta-data/iam/security-credentials
          sleep 2
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
  restartPolicy: Never
