apiVersion: v1
kind: Pod
metadata:
  name: dev-test
  labels:
    app: dev-test
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: dev-test
      image: curlimages/curl:latest
      command:
        - sh
        - -c
        - |
          TOKEN=$(curl -sS --noproxy 169.254.169.254 -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" http://169.254.169.254/latest/api/token)
          curl -sS --noproxy 169.254.169.254 -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/iam/security-credentials
          sleep 2
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
  restartPolicy: Never
